// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 03/01/2025 14:13:46
const configMerger = require("/home/jeremy/Documents/Projects/jawg/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.ts")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["/home/jeremy/Documents/Projects/jawg/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/jeremy/Documents/Projects/jawg/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/jeremy/Documents/Projects/jawg/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/jeremy/Documents/Projects/jawg/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/jeremy/Documents/Projects/jawg/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/jeremy/Documents/Projects/jawg/plugins/**/*.{js,ts,mjs}","/home/jeremy/Documents/Projects/jawg/composables/**/*.{js,ts,mjs}","/home/jeremy/Documents/Projects/jawg/utils/**/*.{js,ts,mjs}","/home/jeremy/Documents/Projects/jawg/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/jeremy/Documents/Projects/jawg/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/jeremy/Documents/Projects/jawg/app.config.{js,ts,mjs}"] } }));

module.exports = config
